### PR TITLE
require.paths removed

### PR DESCRIPTION
**Pull request by rodzyn**
Fixing require.path issues in node 0.5.x and higher (maybe it could be done better, but it works...)

### CODE REVIEW

**Comment by raoulmillais** [comment]
Nice.  +1 for this.  require.paths has been deprecated for a while now and maintaining a separate fork isn't ideal.

**Comment by sublimino** [comment]
+1 Thanks for the patch!

**Comment by DavidArno** [comment]
(updated as part of the problem was due to my ignorance over the need to use --global with npm on Windows to install it correctly)

Hi,

I'm not sure if the problem I'm having is due to the change you have made, or whether jessie isn't really designed for use with Windows.

I installed jessie with node 0.6 on Windows by installing from this fork.  However, I can only get it to work with .js specs, not with coffeescript. For example,

 describe("Simple test", function() {
     it("should work", function() {
         expect (1+1).toEqual(2);
     });
     it("should fail", function() {
         expect (1+1).toEqual(3);
     });
 });

works as expected and results in:

.F

Failures:

  1) Simple test should fail.
     Expected 2 to equal 3.
     # at [object Object].<anonymous> (c:\development\coffee\projects\GameOfLife\specs\really_basic_spec.js:6:22)

Completed in 0.035 seconds
2 examples, 1 failure

However, the equivalent coffeescript spec:

 describe "Simple test", ->
     it "should work", ->
         expect (1+1).toEqual(2)
     it "should fail", ->
         expect (1+1).toEqual(3)

results in the following error:
...\specs\really_basic_spec.coffee:1
cribe "Simple te
      ^^^^^^^^^^^^^
Jessie failed to start. Here's some info about the problem:
SyntaxError: Unexpected string
    at Module._compile (module.js:427:25)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at C:\Users\david\AppData\Roaming\jessie\lib\jessie\runner.js:11:36
    at Array.forEach (native)
    at [object Object].run (C:\Users\david\AppData\Roaming\jessie\lib\jessie\runner.js:11:11)
    at Object.run (C:\Users\david\AppData\Roaming\jessie\lib\jessie.js:11:47)

As node,js didn't work well on Windows prior to 0.6 and as 0.5 broke previous version of jessie, I cannot test this in other configurations. Hopefully there's sufficient info here though to enable you to tell me whether this pull request breaks coffeescript or if there is another problem.

**Comment by marcinbunsch** [comment]
Merging it in, will push it out ASAP

**Pull request merged**
