### PR TITLE
Added continuous test runner -- Jezebel

### PR DESCRIPTION
**Pull request by benrady**
Jezebel is a continuous test runner and REPL wrapper for Jessie. See more info the in the updated docs.

### CODE REVIEW

**Comment by marcinbunsch** [comment]
Wow, that looks really interesting - let me take some time to review that (hopefully will be able to do do this over the weekend). 

One question - why is cli included in the project? Couldn't it be loaded as an npm dependency?

**Comment by benrady** [comment]
My next step is probably to add some user configuration goodness by looking
for, and optionally loading, a file called .jezebel from the working
directory. That module would get mixed into the REPL to let the user define
their own project specific functions and provide handlers for test runner
events (onRed, onGreen, etc...)

Adding cli was unintentional. I removed it and added a .gitignore.

Ben

**Comment by marcinbunsch** [comment]
+1 on the .jezebel file, really neat idea

I took a quick look at runTests() - I like the idea of running the specs in a separate process - I think it's the simplest, safest and - in result - the best approach. I believe that Ruby autotest works in a similar way? It's not the fastest solution, but the most portable.

What do you think about running specific spec file when a file is modified? Like when I save lib/jessie/finder.js, the spec/jessie/finder_spec.js is run? Maybe as an option in .jezebel?

**Comment by benrady** [comment]
Already pushed the .jezebel file change. Pull at your leisure.

I think when you change a spec, it should just run that spec. When you
change a file, it should run all the specs, UNLESS.....

...one feature I'd like to add is a focus() function. You could say:

> focus('spec/models')

or

> focus('spec/models/user_spec.js')

And it would only run that individual file, or the specs in that directory,
until you call unfocus(). We might even treat the list of focused files as a
stack, so every time you call unfocus, it would pop back to your last focus
call (with 'spec' being the permanent root of the stack).

What do you think?

Ben

**Comment by marcinbunsch** [comment]
Hi Ben

I played around with Jezebel, it's really sweet! I implemented one pending spec, you can see it in this commit:
https://github.com/futuresimple/jessie/commit/f945eefd874450bd81d152d23f3e76d1001d8027

I exported the settings object so it is available via require('jezebel').settings as it allows testing with different settings. What do you think about this solution? I'd love to hear your feedback on it as this pending spec is the only thing stopping me from merging jezebel into master :)

Also, one small change - I moved the startRepl function to be next to evalInRepl, to have them closer to each other.

**Comment by benrady** [comment]
Glad you like it. I made some additional changes over the weekend, but I
haven't sent you a new pull request because I'm starting to think that it
might make more sense to package Jezebel as a separate project than depended
on jessie, rather than part of it. As you saw, my attempts to integrate
jessie as an in-process runner didn't really work out. While it would be
really cool to be able to make the results of each test run available in the
REPL, out-of-process execution is the way to go.

What do you think?

Ben

**Comment by marcinbunsch** [comment]
I gave it some thought I agree with you - Jezebel should be a separate project. It extends jessie the same way autotest extends rspec. Also it gives you more flexibility in developing it. I'll add a link to it in jessie's README.

**Pull request closed without merging**
